annealing:
  end_pct: 0.6
  start_pct: 0.0
  type: linear
images:
  apodization_border: 14
  n_pixel: 96
  pix_size: 0.0462
  remove_gradient_apodization: true
initialization:
  modes_std: 0.0
  object: contrast
object1:
  cutoff:
  - 0.8
  - 0.85
  image_filter: scharmer
  s_u_joint: 100.0
  wavelength: 6567.0
object2:
  cutoff:
  - 0.8
  - 0.85
  image_filter: scharmer
  s_u_joint: 100.0
  wavelength: 6563.0
optimization:
  filter_loss: wiener
  gpu: 0
  loss_type: joint
  lr_modes: 0.05
  lr_obj: 0.02
  lr_prior: 0.2
  softplus_scale: 1.0
  transform: softplus
priors:
  K:
    mean: 10.0
    sigma: 1.0
  p:
    mean: 2.0
    sigma: 1.0
  v0:
    mean: 0.1
    sigma: 1.0
psf:
  jitter: fast
  model: kl
  nmax_modes: 90
  remove_tt: true
regularization:
  iuwt1:
    lambda: 0.001
    nbands: 5
    variable: object
telescope:
  central_obscuration: 40.0
  diameter: 144.0
